version: '2'
services:
  web:
    build: ./web
    links:
    - db
    ports:
    - "5000:5000"

  db:
    restart: always
    image: postgres
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: "marti"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /Users/marti/server/pg_data/data:/var/lib/postgresql/data/pgdata


