version: '2'

services:
  web:
    restart: always
    build: ./web
    volumes:
      - /app/web/project/static
    depends_on:
      - db
    links:
    - db
    ports:
    - "8000:8000"
#    expose:
#      - "8000"
    command: gunicorn -w 2 -b :8000 project.app:app

  db:
    restart: always
    image: postgres
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: "marti"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /Users/marti/server/pg_data/data:/var/lib/postgresql/data/pgdata
